/**
 * This file is part of ObjectFabric (http://objectfabric.org).
 *
 * ObjectFabric is licensed under the Apache License, Version 2.0, the terms
 * of which may be found at http://www.apache.org/licenses/LICENSE-2.0.html.
 * 
 * Copyright ObjectFabric Inc.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

package org.objectfabric;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

public class SerializationTestReaderUnknown extends org.objectfabric.SerializationTest.TestReader {

    private int _index;

    @Override
    public void run() {
        for (;;) {
            switch (_index) {
                case 0: {
                    break;
                }
                case 1: {
                    break;
                }
                case 2: {
                    java.lang.Boolean value = (java.lang.Boolean) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 3: {
                    java.lang.Boolean value = (java.lang.Boolean) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(Boolean.TRUE));
                    break;
                }
                case 4: {
                    java.lang.Boolean value = (java.lang.Boolean) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(Boolean.FALSE));
                    break;
                }
                case 5: {
                    break;
                }
                case 6: {
                    break;
                }
                case 7: {
                    break;
                }
                case 8: {
                    java.lang.Byte value = (java.lang.Byte) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 9: {
                    break;
                }
                case 10: {
                    break;
                }
                case 11: {
                    break;
                }
                case 12: {
                    java.lang.Character value = (java.lang.Character) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 13: {
                    break;
                }
                case 14: {
                    break;
                }
                case 15: {
                    break;
                }
                case 16: {
                    java.lang.Short value = (java.lang.Short) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 17: {
                    break;
                }
                case 18: {
                    break;
                }
                case 19: {
                    break;
                }
                case 20: {
                    java.lang.Integer value = (java.lang.Integer) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 21: {
                    break;
                }
                case 22: {
                    break;
                }
                case 23: {
                    break;
                }
                case 24: {
                    java.lang.Long value = (java.lang.Long) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 25: {
                    break;
                }
                case 26: {
                    break;
                }
                case 27: {
                    break;
                }
                case 28: {
                    java.lang.Float value = (java.lang.Float) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 29: {
                    break;
                }
                case 30: {
                    break;
                }
                case 31: {
                    break;
                }
                case 32: {
                    java.lang.Double value = (java.lang.Double) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 33: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 34: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(""));
                    break;
                }
                case 35: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("\u0000"));
                    break;
                }
                case 36: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("\u00FF"));
                    break;
                }
                case 37: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("\u0AFF"));
                    break;
                }
                case 38: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("\u7FFF"));
                    break;
                }
                case 39: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("\uFFFF"));
                    break;
                }
                case 40: {
                    java.lang.String value = (java.lang.String) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals("ffqsdfqfezghrtghrgrfgzefzeqfzeqfqzefqzefqzefqzeefqzefqzefsdqfsdghfgzegqzefqsdfqzefqezfqzefqze'"));
                    break;
                }
                case 41: {
                    java.util.Date value = (java.util.Date) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 42: {
                    java.util.Date value = (java.util.Date) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.util.Date(4558621531843L)));
                    break;
                }
                case 43: {
                    java.util.Date value = (java.util.Date) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.util.Date(0)));
                    break;
                }
                case 44: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 45: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("0")));
                    break;
                }
                case 46: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("-0")));
                    break;
                }
                case 47: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("45")));
                    break;
                }
                case 48: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("-45")));
                    break;
                }
                case 49: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("1237987")));
                    break;
                }
                case 50: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("-1237987")));
                    break;
                }
                case 51: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("1237987898798797464864181688684513518313131813113513")));
                    break;
                }
                case 52: {
                    java.math.BigInteger value = (java.math.BigInteger) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigInteger("-1237987898798797464864181688684513518313131813113513")));
                    break;
                }
                case 53: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value == (null));
                    break;
                }
                case 54: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "0")));
                    break;
                }
                case 55: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-0")));
                    break;
                }
                case 56: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "45")));
                    break;
                }
                case 57: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-45")));
                    break;
                }
                case 58: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "123798789879879.456464")));
                    break;
                }
                case 59: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-123798789879879.456464")));
                    break;
                }
                case 60: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "0.000000000000078")));
                    break;
                }
                case 61: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-0.000000000000078")));
                    break;
                }
                case 62: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "2.0e5")));
                    break;
                }
                case 63: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-2.0e5")));
                    break;
                }
                case 64: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "789.046544654846468789486e13")));
                    break;
                }
                case 65: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-789.046544654846468789486e13")));
                    break;
                }
                case 66: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "789.046544654846468789486e-13")));
                    break;
                }
                case 67: {
                    java.math.BigDecimal value = (java.math.BigDecimal) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(value.equals(new java.math.BigDecimal( "-789.046544654846468789486e-13")));
                    break;
                }
                case 68: {
                    byte[] value = (byte[]) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(java.util.Arrays.equals(value, null));
                    break;
                }
                case 69: {
                    byte[] value = (byte[]) org.objectfabric.UnknownObjectSerializer.read(this);

                    if (interrupted())
                        return;

                    org.objectfabric.Debug.assertAlways(java.util.Arrays.equals(value, new byte[] { 45, 88 }));
                    break;
                }
                default:
                    return;
            }

            _index++;
        }
    }

    @Override
    public boolean isDone() {
        return _index == 70;
    }
}
