/**
 * This file is part of ObjectFabric (http://objectfabric.org).
 *
 * ObjectFabric is licensed under the Apache License, Version 2.0, the terms
 * of which may be found at http://www.apache.org/licenses/LICENSE-2.0.html.
 * 
 * Copyright ObjectFabric Inc.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

package org.objectfabric;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

public class SerializationTestWriterUnknown extends org.objectfabric.SerializationTest.TestWriter {

    private int _index;

    @Override
    public void run() {
        for (;;) {
            switch (_index) {
                case 0: {
                    break;
                }
                case 1: {
                    break;
                }
                case 2: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 3: {
                    org.objectfabric.UnknownObjectSerializer.write(this, Boolean.TRUE);

                    if (interrupted())
                        return;
                    break;
                }
                case 4: {
                    org.objectfabric.UnknownObjectSerializer.write(this, Boolean.FALSE);

                    if (interrupted())
                        return;
                    break;
                }
                case 5: {
                    break;
                }
                case 6: {
                    break;
                }
                case 7: {
                    break;
                }
                case 8: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 9: {
                    break;
                }
                case 10: {
                    break;
                }
                case 11: {
                    break;
                }
                case 12: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 13: {
                    break;
                }
                case 14: {
                    break;
                }
                case 15: {
                    break;
                }
                case 16: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 17: {
                    break;
                }
                case 18: {
                    break;
                }
                case 19: {
                    break;
                }
                case 20: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 21: {
                    break;
                }
                case 22: {
                    break;
                }
                case 23: {
                    break;
                }
                case 24: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 25: {
                    break;
                }
                case 26: {
                    break;
                }
                case 27: {
                    break;
                }
                case 28: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 29: {
                    break;
                }
                case 30: {
                    break;
                }
                case 31: {
                    break;
                }
                case 32: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 33: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 34: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "");

                    if (interrupted())
                        return;
                    break;
                }
                case 35: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "\u0000");

                    if (interrupted())
                        return;
                    break;
                }
                case 36: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "\u00FF");

                    if (interrupted())
                        return;
                    break;
                }
                case 37: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "\u0AFF");

                    if (interrupted())
                        return;
                    break;
                }
                case 38: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "\u7FFF");

                    if (interrupted())
                        return;
                    break;
                }
                case 39: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "\uFFFF");

                    if (interrupted())
                        return;
                    break;
                }
                case 40: {
                    org.objectfabric.UnknownObjectSerializer.write(this, "ffqsdfqfezghrtghrgrfgzefzeqfzeqfqzefqzefqzefqzeefqzefqzefsdqfsdghfgzegqzefqsdfqzefqezfqzefqze'");

                    if (interrupted())
                        return;
                    break;
                }
                case 41: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 42: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.util.Date(4558621531843L));

                    if (interrupted())
                        return;
                    break;
                }
                case 43: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.util.Date(0));

                    if (interrupted())
                        return;
                    break;
                }
                case 44: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 45: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("0"));

                    if (interrupted())
                        return;
                    break;
                }
                case 46: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("-0"));

                    if (interrupted())
                        return;
                    break;
                }
                case 47: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("45"));

                    if (interrupted())
                        return;
                    break;
                }
                case 48: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("-45"));

                    if (interrupted())
                        return;
                    break;
                }
                case 49: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("1237987"));

                    if (interrupted())
                        return;
                    break;
                }
                case 50: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("-1237987"));

                    if (interrupted())
                        return;
                    break;
                }
                case 51: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("1237987898798797464864181688684513518313131813113513"));

                    if (interrupted())
                        return;
                    break;
                }
                case 52: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigInteger("-1237987898798797464864181688684513518313131813113513"));

                    if (interrupted())
                        return;
                    break;
                }
                case 53: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 54: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "0"));

                    if (interrupted())
                        return;
                    break;
                }
                case 55: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-0"));

                    if (interrupted())
                        return;
                    break;
                }
                case 56: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "45"));

                    if (interrupted())
                        return;
                    break;
                }
                case 57: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-45"));

                    if (interrupted())
                        return;
                    break;
                }
                case 58: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "123798789879879.456464"));

                    if (interrupted())
                        return;
                    break;
                }
                case 59: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-123798789879879.456464"));

                    if (interrupted())
                        return;
                    break;
                }
                case 60: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "0.000000000000078"));

                    if (interrupted())
                        return;
                    break;
                }
                case 61: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-0.000000000000078"));

                    if (interrupted())
                        return;
                    break;
                }
                case 62: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "2.0e5"));

                    if (interrupted())
                        return;
                    break;
                }
                case 63: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-2.0e5"));

                    if (interrupted())
                        return;
                    break;
                }
                case 64: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "789.046544654846468789486e13"));

                    if (interrupted())
                        return;
                    break;
                }
                case 65: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-789.046544654846468789486e13"));

                    if (interrupted())
                        return;
                    break;
                }
                case 66: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "789.046544654846468789486e-13"));

                    if (interrupted())
                        return;
                    break;
                }
                case 67: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-789.046544654846468789486e-13"));

                    if (interrupted())
                        return;
                    break;
                }
                case 68: {
                    org.objectfabric.UnknownObjectSerializer.write(this, null);

                    if (interrupted())
                        return;
                    break;
                }
                case 69: {
                    org.objectfabric.UnknownObjectSerializer.write(this, new byte[] { 45, 88 });

                    if (interrupted())
                        return;
                    break;
                }
                default:
                    return;
            }

            _index++;
        }
    }

}
