/**
 * Copyright (c) ObjectFabric Inc. All rights reserved.
 *
 * This file is part of ObjectFabric (objectfabric.com).
 *
 * ObjectFabric is licensed under the Apache License, Version 2.0, the terms
 * of which may be found at http://www.apache.org/licenses/LICENSE-2.0.html.
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

package of4gwt;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

@SuppressWarnings({ "hiding", "unchecked", "static-access" })
abstract class IndexBase extends of4gwt.TGeneratedFields32 {

    protected IndexBase() {
        this(of4gwt.Transaction.getDefaultTrunk());
    }

    protected IndexBase(of4gwt.Transaction trunk) {
        this(new Version(null, FIELD_COUNT), trunk);
    }

    protected IndexBase(of4gwt.TObject.Version shared, of4gwt.Transaction trunk) {
        super(shared, trunk);
    }

    public static final of4gwt.TType TYPE = new of4gwt.TType(of4gwt.DefaultObjectModel.getInstance(), of4gwt.DefaultObjectModelBase.COM_OBJECTFABRIC_INDEX_CLASS_ID);

    public static final int FIELD_COUNT = 0;

    @Override
    public int getFieldCount() {
        return FIELD_COUNT;
    }

    @Override
    public java.lang.String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    @SuppressWarnings("static-access")
    public static java.lang.String getFieldNameStatic(int index) {
        switch (index) {
            default:
                throw new IllegalArgumentException();
        }
    }

    @Override
    public java.lang.Class getFieldClass(int index) {
        return getFieldClassStatic(index);
    }

    @SuppressWarnings("static-access")
    public static java.lang.Class getFieldClassStatic(int index) {
        switch (index) {
            default:
                throw new IllegalArgumentException();
        }
    }

    // Methods

    protected static final int METHOD_0 = 0;

    /**
     * 
     */
    protected final of4gwt.TObject fetch(byte[] ref) {
        return fetch(ref, getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Specifies the Executor or TaskScheduler that will run the method. For replicated objects, the method runs by default on the site the object has been created, using site's method executor.
     */
    protected final of4gwt.TObject fetch(byte[] ref, of4gwt.misc.Executor executor) {
        if (executor == of4gwt.misc.TransparentExecutor.getInstance())
            return fetchImplementation(ref);
        else {
            of4gwt.misc.Future<of4gwt.TObject> future_ = fetchAsync(ref, getNopCallback_objectfabric(), null, executor);

            try {
                return future_.get();
            } catch (of4gwt.misc.InterruptedException ex_) {
                throw new RuntimeException(ex_);
            } catch (of4gwt.misc.ExecutionException ex_) {
                if (ex_.getCause() instanceof RuntimeException)
                    throw (RuntimeException) ex_.getCause();

                throw new RuntimeException(ex_.getCause());
            }
        }
    }

    /**
     * Asynchronous version.
     */
    protected final of4gwt.misc.Future<of4gwt.TObject> fetchAsync(byte[] ref, com.google.gwt.user.client.rpc.AsyncCallback<of4gwt.TObject> callback) {
        return fetchAsync(ref, callback, getDefaultAsyncOptions_objectfabric(), getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Asynchronous version, with options for the callback.
     */
    protected final of4gwt.misc.Future<of4gwt.TObject> fetchAsync(byte[] ref, com.google.gwt.user.client.rpc.AsyncCallback<of4gwt.TObject> callback, of4gwt.AsyncOptions asyncOptions) {
        return fetchAsync(ref, callback, asyncOptions, getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Asynchronous version, with options for the callback, and specifies the Executor or TaskScheduler that will run the method. For replicated objects,
     * the method runs by default on the site the object has been created. @see Site.getMethodExecutor() to specify an execution site.
     */
    protected final of4gwt.misc.Future<of4gwt.TObject> fetchAsync(byte[] ref, com.google.gwt.user.client.rpc.AsyncCallback<of4gwt.TObject> callback, of4gwt.AsyncOptions asyncOptions, of4gwt.misc.Executor executor) {
        if (executor == of4gwt.misc.TransparentExecutor.getInstance()) {
            of4gwt.TObject result_ = null;
            java.lang.Throwable throwable_ = null;

            try {
                result_ = fetchImplementation(ref);
            } catch (java.lang.Throwable t_) {
                throwable_ = t_;
            }

            return getCompletedFuture_objectfabric(result_, throwable_, callback, asyncOptions);
        } else {
            of4gwt.DefaultObjectModel.Method1.Version version_ = (of4gwt.DefaultObjectModel.Method1.Version) createVersion_objectfabric(of4gwt.DefaultObjectModel.Method1.INSTANCE);

            if (ref != null) {
                version_._ref = ref;
                version_.setBit(of4gwt.DefaultObjectModel.Method1.REF_INDEX);
            }

            of4gwt.TObject.UserTObject.LocalMethodCall call_ = new of4gwt.TObject.UserTObject.LocalMethodCall(this, of4gwt.DefaultObjectModel.Method1.INSTANCE, version_, METHOD_0, callback, asyncOptions);
            executor.execute(call_);
            return call_;
        }
    }

    /**
     * Override to implement the method.
     */
    protected of4gwt.TObject fetchImplementation(byte[] ref) {
        throw new RuntimeException(of4gwt.Strings.MISSING_METHOD_CALL_IMPLEMENTATION);
    }

    /**
     * Override to implement the method asynchronously.
     */
    protected void fetchImplementationAsync(byte[] ref, of4gwt.MethodCall call) {
        try {
            call.set(fetchImplementation(ref));
        } catch (java.lang.Throwable t_) {
            call.setException(t_);
        }
    }

    @SuppressWarnings({ "static-access", "cast" })
    @Override
    protected void invoke_objectfabric(of4gwt.MethodCall call) {
        switch (getMethodCallIndex_objectfabric(call)) {
            case METHOD_0: {
                of4gwt.DefaultObjectModel.Method1.Version version_ = (of4gwt.DefaultObjectModel.Method1.Version) getMethodVersion_objectfabric(call);
                byte[] ref = version_ != null ? (byte[]) version_._ref : null;

                try {
                    fetchImplementationAsync(ref, call);
                } catch (java.lang.Throwable t_) {
                    call.setException(t_);
                }

                break;
            }
            default: {
                super.invoke_objectfabric(call);
                break;
            }
        }
    }

    @SuppressWarnings({ "static-access", "cast" })
    @Override
    protected void setResult_objectfabric(of4gwt.TObject.Version version, int index, java.lang.Object result) {
        switch (index) {
            case METHOD_0: {
                ((of4gwt.DefaultObjectModel.Method1.Version) version)._return_objectfabric = (of4gwt.TObject) result;
                ((of4gwt.DefaultObjectModel.Method1.Version) version).setBit(of4gwt.DefaultObjectModel.Method1.RETURN_OBJECTFABRIC_INDEX);
                break;
            }
            default: {
                super.setResult_objectfabric(version, index, result);
                break;
            }
        }
    }

    @SuppressWarnings("static-access")
    @Override
    protected void setError_objectfabric(of4gwt.TObject.Version version, int index, java.lang.String error) {
        switch (index) {
            case METHOD_0: {
                ((of4gwt.DefaultObjectModel.Method1.Version) version)._error_objectfabric = error;
                ((of4gwt.DefaultObjectModel.Method1.Version) version).setBit(of4gwt.DefaultObjectModel.Method1.ERROR_OBJECTFABRIC_INDEX);
                break;
            }
            default: {
                super.setError_objectfabric(version, index, error);
                break;
            }
        }
    }

    @SuppressWarnings("static-access")
    @Override
    protected void getResultOrError_objectfabric(of4gwt.MethodCall call) {
        switch (getMethodCallIndex_objectfabric(call)) {
            case METHOD_0: {
                of4gwt.DefaultObjectModel.Method1.Version version = (of4gwt.DefaultObjectModel.Method1.Version) getMethodVersion_objectfabric(call);

                if (version == null || version._error_objectfabric == null)
                    setDirect(call, version != null ? version._return_objectfabric : null);
                else
                    setExceptionDirect(call, new of4gwt.misc.ReplicatedException(version._error_objectfabric));

                break;
            }
            default: {
                super.getResultOrError_objectfabric(call);
                break;
            }
        }
    }

    protected static class Version extends of4gwt.TGeneratedFields32.Version {

        static {
        }

        public Version(of4gwt.TGeneratedFields32.Version shared, int length) {
            super(shared, length);
        }

        @Override
        public java.lang.Object getAsObject(int index) {
            switch (index) {
                default:
                    return super.getAsObject(index);
            }
        }

        @Override
        public void setAsObject(int index, java.lang.Object value) {
            switch (index) {
                default:
                    super.setAsObject(index, value);
                    break;
            }
        }

        @Override
        public of4gwt.TObject.Version merge(of4gwt.TObject.Version target, of4gwt.TObject.Version next, int flags) {
            IndexBase.Version merged = (IndexBase.Version) super.merge(target, next, flags);
            return merged;
        }

        @Override
        public void writeWrite(of4gwt.Writer writer, int index) {
            if (writer.interrupted())
                writer.resume();

            switch (index) {
                default: {
                    super.writeWrite(writer, index);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public void readWrite(of4gwt.Reader reader, int index) {
            if (reader.interrupted())
                reader.resume();

            switch (index) {
                default: {
                    super.readWrite(reader, index);

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public of4gwt.TObject.Version createVersion() {
            return new IndexBase.Version(this, FIELD_COUNT);
        }

        @Override
        public int getClassId() {
            return of4gwt.DefaultObjectModelBase.COM_OBJECTFABRIC_INDEX_CLASS_ID;
        }

        @SuppressWarnings("static-access")
        @Override
        public of4gwt.ObjectModel getObjectModel() {
            return of4gwt.DefaultObjectModel.getInstance();
        }
    }
}
