/**
 * Copyright (c) ObjectFabric Inc. All rights reserved.
 *
 * This file is part of ObjectFabric (objectfabric.com).
 *
 * ObjectFabric is licensed under the Apache License, Version 2.0, the terms
 * of which may be found at http://www.apache.org/licenses/LICENSE-2.0.html.
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

package of4gwt;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

@SuppressWarnings({ "hiding", "unchecked", "static-access", "unused" })
abstract class SessionBase extends of4gwt.TGeneratedFields32 {

    protected SessionBase(of4gwt.Site originImpl, of4gwt.Transaction trunkImpl) {
        this(of4gwt.Transaction.getDefaultTrunk(), originImpl, trunkImpl);
    }

    protected SessionBase(of4gwt.Transaction trunk, of4gwt.Site originImpl, of4gwt.Transaction trunkImpl) {
        this(new Version(null, FIELD_COUNT), trunk, originImpl, trunkImpl);
    }

    protected SessionBase(of4gwt.TObject.Version shared, of4gwt.Transaction trunk, of4gwt.Site originImpl, of4gwt.Transaction trunkImpl) {
        super(shared, trunk);

        ((Version) shared)._originImpl = shared.mergeTObject(((Version) shared)._originImpl, originImpl);

        if (originImpl != null)
            ((Version) shared).setBit(ORIGIN_IMPL_INDEX);

        ((Version) shared)._trunkImpl = shared.mergeTObject(((Version) shared)._trunkImpl, trunkImpl);

        if (trunkImpl != null)
            ((Version) shared).setBit(TRUNK_IMPL_INDEX);
    }

    public static final of4gwt.TType TYPE = new of4gwt.TType(of4gwt.DefaultObjectModel.getInstance(), of4gwt.DefaultObjectModelBase.COM_OBJECTFABRIC_SESSION_CLASS_ID);

    protected final of4gwt.Site getOriginImpl() {
        Version v = (Version) getSharedVersion_objectfabric();
        return (of4gwt.Site) getUserTObject_objectfabric(v._originImpl);
    }

    protected final of4gwt.Transaction getTrunkImpl() {
        Version v = (Version) getSharedVersion_objectfabric();
        return (of4gwt.Transaction) getUserTObject_objectfabric(v._trunkImpl);
    }

    protected static final int ORIGIN_IMPL_INDEX = 0;

    protected static final java.lang.String ORIGIN_IMPL_NAME = "originImpl";

    protected static final of4gwt.TType ORIGIN_IMPL_TYPE = of4gwt.Site.TYPE;

    protected static final int TRUNK_IMPL_INDEX = 1;

    protected static final java.lang.String TRUNK_IMPL_NAME = "trunkImpl";

    protected static final of4gwt.TType TRUNK_IMPL_TYPE = of4gwt.Transaction.TYPE;

    public static final int FIELD_COUNT = 2;

    @Override
    public int getFieldCount() {
        return FIELD_COUNT;
    }

    @Override
    public java.lang.String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    @SuppressWarnings("static-access")
    public static java.lang.String getFieldNameStatic(int index) {
        switch (index) {
            case ORIGIN_IMPL_INDEX:
                return ORIGIN_IMPL_NAME;
            case TRUNK_IMPL_INDEX:
                return TRUNK_IMPL_NAME;
            default:
                throw new IllegalArgumentException();
        }
    }

    @Override
    public  of4gwt.TType getFieldType(int index) {
        return getFieldTypeStatic(index);
    }

    @SuppressWarnings("static-access")
    public static of4gwt.TType getFieldTypeStatic(int index) {
        switch (index) {
            case ORIGIN_IMPL_INDEX:
                return ORIGIN_IMPL_TYPE;
            case TRUNK_IMPL_INDEX:
                return TRUNK_IMPL_TYPE;
            default:
                throw new IllegalArgumentException();
        }
    }

    protected static class Version extends of4gwt.TGeneratedFields32.Version {

        public of4gwt.TObject _originImpl;

        public of4gwt.TObject _trunkImpl;

        private static final int _readOnlys;

        static {
            int readOnlys = 0;
            readOnlys = setBit(readOnlys, ORIGIN_IMPL_INDEX);
            readOnlys = setBit(readOnlys, TRUNK_IMPL_INDEX);
            _readOnlys = readOnlys;
        }

        public Version(of4gwt.TGeneratedFields32.Version shared, int length) {
            super(shared, length);
        }

        @Override
        public java.lang.Object getAsObject(int index) {
            switch (index) {
                case ORIGIN_IMPL_INDEX:
                    return getUserTObject_objectfabric(_originImpl);
                case TRUNK_IMPL_INDEX:
                    return getUserTObject_objectfabric(_trunkImpl);
                default:
                    return super.getAsObject(index);
            }
        }

        @Override
        public void setAsObject(int index, java.lang.Object value) {
            switch (index) {
                case ORIGIN_IMPL_INDEX:
                    _originImpl = (of4gwt.Site) value;
                    break;
                case TRUNK_IMPL_INDEX:
                    _trunkImpl = (of4gwt.Transaction) value;
                    break;
                default:
                    super.setAsObject(index, value);
                    break;
            }
        }

        @Override
        public of4gwt.TObject.Version merge(of4gwt.TObject.Version target, of4gwt.TObject.Version next, int flags) {
            SessionBase.Version source = (SessionBase.Version) next;
            SessionBase.Version merged = (SessionBase.Version) super.merge(target, next, flags);

            if (source.hasBits()) {
                if (source.getBit(ORIGIN_IMPL_INDEX))
                    merged._originImpl = mergeTObject(merged._originImpl, source._originImpl);

                if (source.getBit(TRUNK_IMPL_INDEX))
                    merged._trunkImpl = mergeTObject(merged._trunkImpl, source._trunkImpl);
            }

            return merged;
        }

        @Override
        public int getReadOnlys() {
            return _readOnlys;
        }

        @Override
        public void writeWrite(of4gwt.Writer writer, int index) {
            if (writer.interrupted())
                writer.resume();

            switch (index) {
                case ORIGIN_IMPL_INDEX: {
                    writer.writeTObject(_originImpl);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
                case TRUNK_IMPL_INDEX: {
                    writer.writeTObject(_trunkImpl);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
                default: {
                    super.writeWrite(writer, index);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public void readWrite(of4gwt.Reader reader, int index) {
            if (reader.interrupted())
                reader.resume();

            switch (index) {
                case ORIGIN_IMPL_INDEX: {
                    SessionBase.Version shared = (SessionBase.Version) getUnion();
                    shared._originImpl = getSharedVersion_objectfabric(reader.readTObject());

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }

                    shared.setBit(ORIGIN_IMPL_INDEX);
                    unsetBit(ORIGIN_IMPL_INDEX);
                    break;
                }
                case TRUNK_IMPL_INDEX: {
                    SessionBase.Version shared = (SessionBase.Version) getUnion();
                    shared._trunkImpl = getSharedVersion_objectfabric(reader.readTObject());

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }

                    shared.setBit(TRUNK_IMPL_INDEX);
                    unsetBit(TRUNK_IMPL_INDEX);
                    break;
                }
                default: {
                    super.readWrite(reader, index);

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public of4gwt.TObject.Version createVersion() {
            return new SessionBase.Version(this, FIELD_COUNT);
        }

        @Override
        public int getClassId() {
            return of4gwt.DefaultObjectModelBase.COM_OBJECTFABRIC_SESSION_CLASS_ID;
        }

        @SuppressWarnings("static-access")
        @Override
        public of4gwt.ObjectModel getObjectModel() {
            return of4gwt.DefaultObjectModel.getInstance();
        }
    }
}
