/**
 * Copyright (c) ObjectFabric Inc. All rights reserved.
 *
 * This file is part of ObjectFabric (objectfabric.com).
 *
 * ObjectFabric is licensed under the Apache License, Version 2.0, the terms
 * of which may be found at http://www.apache.org/licenses/LICENSE-2.0.html.
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

package of4gwt;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

public class SerializationTestWriterUnknown extends of4gwt.SerializationTest.TestWriter {

    private int _index;

    @Override
    public void run() {
        for (;;) {
            switch (_index) {
                case 0: {
                    break;
                }
                case 1: {
                    break;
                }
                case 2: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 3: {
                    of4gwt.UnknownObjectSerializer.write(this, Boolean.TRUE, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 4: {
                    of4gwt.UnknownObjectSerializer.write(this, Boolean.FALSE, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 5: {
                    break;
                }
                case 6: {
                    break;
                }
                case 7: {
                    break;
                }
                case 8: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 9: {
                    break;
                }
                case 10: {
                    break;
                }
                case 11: {
                    break;
                }
                case 12: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 13: {
                    break;
                }
                case 14: {
                    break;
                }
                case 15: {
                    break;
                }
                case 16: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 17: {
                    break;
                }
                case 18: {
                    break;
                }
                case 19: {
                    break;
                }
                case 20: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 21: {
                    break;
                }
                case 22: {
                    break;
                }
                case 23: {
                    break;
                }
                case 24: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 25: {
                    break;
                }
                case 26: {
                    break;
                }
                case 27: {
                    break;
                }
                case 28: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 29: {
                    break;
                }
                case 30: {
                    break;
                }
                case 31: {
                    break;
                }
                case 32: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 33: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 34: {
                    of4gwt.UnknownObjectSerializer.write(this, "", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 35: {
                    of4gwt.UnknownObjectSerializer.write(this, "\u0000", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 36: {
                    of4gwt.UnknownObjectSerializer.write(this, "\u00FF", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 37: {
                    of4gwt.UnknownObjectSerializer.write(this, "\u0AFF", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 38: {
                    of4gwt.UnknownObjectSerializer.write(this, "\u7FFF", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 39: {
                    of4gwt.UnknownObjectSerializer.write(this, "\uFFFF", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 40: {
                    of4gwt.UnknownObjectSerializer.write(this, "$^%���%��%���%�", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 41: {
                    of4gwt.UnknownObjectSerializer.write(this, "ffqsdfqfezghrtghrgrfgzefzeqfzeqfqzefqzefqzefqzeefqzefqzefsdqfsdghfgzegqzefqsdfqzefqezfqzefqze'", -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 42: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 43: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.util.Date(4558621531843L), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 44: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.util.Date(0), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 45: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 46: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("0"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 47: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("-0"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 48: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("45"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 49: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("-45"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 50: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("1237987"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 51: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("-1237987"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 52: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("1237987898798797464864181688684513518313131813113513"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 53: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigInteger("-1237987898798797464864181688684513518313131813113513"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 54: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 55: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "0"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 56: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-0"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 57: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "45"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 58: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-45"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 59: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "123798789879879.456464"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 60: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-123798789879879.456464"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 61: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "0.000000000000078"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 62: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-0.000000000000078"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 63: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "2.0e5"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 64: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-2.0e5"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 65: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "789.046544654846468789486e13"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 66: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-789.046544654846468789486e13"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 67: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "789.046544654846468789486e-13"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 68: {
                    of4gwt.UnknownObjectSerializer.write(this, new java.math.BigDecimal( "-789.046544654846468789486e-13"), -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 69: {
                    of4gwt.UnknownObjectSerializer.write(this, null, -1);

                    if (interrupted())
                        return;
                    break;
                }
                case 70: {
                    of4gwt.UnknownObjectSerializer.write(this, new byte[] { 45, 88 }, -1);

                    if (interrupted())
                        return;
                    break;
                }
                default:
                    return;
            }

            _index++;
        }
    }

}
