
package of4gwt;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

@SuppressWarnings({ "hiding", "unchecked", "static-access", "unused" })
public class ShiroStore extends of4gwt.TGeneratedFields32 {

    public ShiroStore() {
        this(of4gwt.Transaction.getDefaultTrunk());
    }

    public ShiroStore(of4gwt.Transaction trunk) {
        this(trunk, new of4gwt.LazyMap<java.lang.String, of4gwt.Account>(trunk), new of4gwt.LazyMap<java.lang.String, java.lang.Object>(trunk));
    }

    public ShiroStore(of4gwt.LazyMap<java.lang.String, of4gwt.Account> accounts, of4gwt.LazyMap<java.lang.String, java.lang.Object> sessions) {
        this(of4gwt.Transaction.getDefaultTrunk(), accounts, sessions);
    }

    public ShiroStore(of4gwt.Transaction trunk, of4gwt.LazyMap<java.lang.String, of4gwt.Account> accounts, of4gwt.LazyMap<java.lang.String, java.lang.Object> sessions) {
        this(new Version(null, FIELD_COUNT), trunk, accounts, sessions);
    }

    protected ShiroStore(of4gwt.TObject.Version shared, of4gwt.Transaction trunk, of4gwt.LazyMap<java.lang.String, of4gwt.Account> accounts, of4gwt.LazyMap<java.lang.String, java.lang.Object> sessions) {
        super(shared, trunk);

        ((Version) shared)._accounts = shared.mergeTObject(((Version) shared)._accounts, accounts);

        if (accounts != null)
            ((Version) shared).setBit(ACCOUNTS_INDEX);

        ((Version) shared)._sessions = shared.mergeTObject(((Version) shared)._sessions, sessions);

        if (sessions != null)
            ((Version) shared).setBit(SESSIONS_INDEX);
    }

    public static final of4gwt.TType TYPE = new of4gwt.TType(of4gwt.ShiroObjectModel.getInstance(), of4gwt.ShiroObjectModel.OF4GWT_SHIROSTORE_CLASS_ID);

    public final of4gwt.LazyMap<java.lang.String, of4gwt.Account> getAccounts() {
        Version v = (Version) getSharedVersion_objectfabric();
        return (of4gwt.LazyMap<java.lang.String, of4gwt.Account>) getUserTObject_objectfabric(v._accounts);
    }

    public final of4gwt.LazyMap<java.lang.String, java.lang.Object> getSessions() {
        Version v = (Version) getSharedVersion_objectfabric();
        return (of4gwt.LazyMap<java.lang.String, java.lang.Object>) getUserTObject_objectfabric(v._sessions);
    }

    public static final int ACCOUNTS_INDEX = 0;

    public static final java.lang.String ACCOUNTS_NAME = "accounts";

    public static final of4gwt.TType ACCOUNTS_TYPE = of4gwt.LazyMap.TYPE;

    public static final int SESSIONS_INDEX = 1;

    public static final java.lang.String SESSIONS_NAME = "sessions";

    public static final of4gwt.TType SESSIONS_TYPE = of4gwt.LazyMap.TYPE;

    public static final int FIELD_COUNT = 2;

    @Override
    public int getFieldCount() {
        return FIELD_COUNT;
    }

    @Override
    public java.lang.String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    @SuppressWarnings("static-access")
    public static java.lang.String getFieldNameStatic(int index) {
        switch (index) {
            case ACCOUNTS_INDEX:
                return ACCOUNTS_NAME;
            case SESSIONS_INDEX:
                return SESSIONS_NAME;
            default:
                throw new IllegalArgumentException();
        }
    }

    @Override
    public  of4gwt.TType getFieldType(int index) {
        return getFieldTypeStatic(index);
    }

    @SuppressWarnings("static-access")
    public static of4gwt.TType getFieldTypeStatic(int index) {
        switch (index) {
            case ACCOUNTS_INDEX:
                return ACCOUNTS_TYPE;
            case SESSIONS_INDEX:
                return SESSIONS_TYPE;
            default:
                throw new IllegalArgumentException();
        }
    }

    protected static class Version extends of4gwt.TGeneratedFields32.Version {

        public of4gwt.TObject _accounts;

        public of4gwt.TObject _sessions;

        private static final int _readOnlys;

        static {
            int readOnlys = 0;
            readOnlys = setBit(readOnlys, ACCOUNTS_INDEX);
            readOnlys = setBit(readOnlys, SESSIONS_INDEX);
            _readOnlys = readOnlys;
        }

        public Version(of4gwt.TGeneratedFields32.Version shared, int length) {
            super(shared, length);
        }

        @Override
        public java.lang.Object getAsObject(int index) {
            switch (index) {
                case ACCOUNTS_INDEX:
                    return getUserTObject_objectfabric(_accounts);
                case SESSIONS_INDEX:
                    return getUserTObject_objectfabric(_sessions);
                default:
                    return super.getAsObject(index);
            }
        }

        @Override
        public void setAsObject(int index, java.lang.Object value) {
            switch (index) {
                case ACCOUNTS_INDEX:
                    _accounts = (of4gwt.LazyMap) value;
                    break;
                case SESSIONS_INDEX:
                    _sessions = (of4gwt.LazyMap) value;
                    break;
                default:
                    super.setAsObject(index, value);
                    break;
            }
        }

        @Override
        public of4gwt.TObject.Version merge(of4gwt.TObject.Version target, of4gwt.TObject.Version next, int flags) {
            ShiroStore.Version source = (ShiroStore.Version) next;
            ShiroStore.Version merged = (ShiroStore.Version) super.merge(target, next, flags);

            if (source.hasBits()) {
                if (source.getBit(ACCOUNTS_INDEX))
                    merged._accounts = mergeTObject(merged._accounts, source._accounts);

                if (source.getBit(SESSIONS_INDEX))
                    merged._sessions = mergeTObject(merged._sessions, source._sessions);
            }

            return merged;
        }

        @Override
        public int getReadOnlys() {
            return _readOnlys;
        }

        @Override
        public void writeWrite(of4gwt.Writer writer, int index) {
            if (writer.interrupted())
                writer.resume();

            switch (index) {
                case ACCOUNTS_INDEX: {
                    writer.writeTObject(_accounts);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
                case SESSIONS_INDEX: {
                    writer.writeTObject(_sessions);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
                default: {
                    super.writeWrite(writer, index);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public void readWrite(of4gwt.Reader reader, int index) {
            if (reader.interrupted())
                reader.resume();

            switch (index) {
                case ACCOUNTS_INDEX: {
                    ShiroStore.Version shared = (ShiroStore.Version) getUnion();
                    shared._accounts = getSharedVersion_objectfabric(reader.readTObject());

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }

                    shared.setBit(ACCOUNTS_INDEX);
                    unsetBit(ACCOUNTS_INDEX);
                    break;
                }
                case SESSIONS_INDEX: {
                    ShiroStore.Version shared = (ShiroStore.Version) getUnion();
                    shared._sessions = getSharedVersion_objectfabric(reader.readTObject());

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }

                    shared.setBit(SESSIONS_INDEX);
                    unsetBit(SESSIONS_INDEX);
                    break;
                }
                default: {
                    super.readWrite(reader, index);

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public of4gwt.TObject.Version createVersion() {
            return new ShiroStore.Version(this, FIELD_COUNT);
        }

        @Override
        public int getClassId() {
            return of4gwt.ShiroObjectModel.OF4GWT_SHIROSTORE_CLASS_ID;
        }

        @SuppressWarnings("static-access")
        @Override
        public of4gwt.ObjectModel getObjectModel() {
            return of4gwt.ShiroObjectModel.getInstance();
        }
    }
}
