
package of4gwt;

//==============================================================================
//                                                                              
//  THIS FILE HAS BEEN GENERATED BY OBJECTFABRIC                                
//                                                                              
//==============================================================================

@SuppressWarnings({ "hiding", "unchecked", "static-access", "unused" })
public class UsernamePasswordSession extends of4gwt.TGeneratedFields32 {

    public UsernamePasswordSession(of4gwt.UsernamePasswordUserManager userManager) {
        this(of4gwt.Transaction.getDefaultTrunk(), userManager);
    }

    public UsernamePasswordSession(of4gwt.Transaction trunk, of4gwt.UsernamePasswordUserManager userManager) {
        this(new Version(null, FIELD_COUNT), trunk, userManager);
    }

    protected UsernamePasswordSession(of4gwt.TObject.Version shared, of4gwt.Transaction trunk, of4gwt.UsernamePasswordUserManager userManager) {
        super(shared, trunk);

        ((Version) shared)._userManager = shared.mergeTObject(((Version) shared)._userManager, userManager);

        if (userManager != null)
            ((Version) shared).setBit(USER_MANAGER_INDEX);
    }

    public static final of4gwt.TType TYPE = new of4gwt.TType(of4gwt.ShiroObjectModel.getInstance(), of4gwt.ShiroObjectModel.OF4GWT_USERNAMEPASSWORDSESSION_CLASS_ID);

    public final of4gwt.UsernamePasswordUserManager getUserManager() {
        Version v = (Version) getSharedVersion_objectfabric();
        return (of4gwt.UsernamePasswordUserManager) getUserTObject_objectfabric(v._userManager);
    }

    public static final int USER_MANAGER_INDEX = 0;

    public static final java.lang.String USER_MANAGER_NAME = "userManager";

    public static final of4gwt.TType USER_MANAGER_TYPE = of4gwt.UsernamePasswordUserManager.TYPE;

    public static final int FIELD_COUNT = 1;

    @Override
    public int getFieldCount() {
        return FIELD_COUNT;
    }

    @Override
    public java.lang.String getFieldName(int index) {
        return getFieldNameStatic(index);
    }

    @SuppressWarnings("static-access")
    public static java.lang.String getFieldNameStatic(int index) {
        switch (index) {
            case USER_MANAGER_INDEX:
                return USER_MANAGER_NAME;
            default:
                throw new IllegalArgumentException();
        }
    }

    @Override
    public  of4gwt.TType getFieldType(int index) {
        return getFieldTypeStatic(index);
    }

    @SuppressWarnings("static-access")
    public static of4gwt.TType getFieldTypeStatic(int index) {
        switch (index) {
            case USER_MANAGER_INDEX:
                return USER_MANAGER_TYPE;
            default:
                throw new IllegalArgumentException();
        }
    }

    // Methods

    protected static final int METHOD_0 = 0;

    protected static final int METHOD_1 = 1;

    protected static final int METHOD_2 = 2;
    /**
     * Creates a session
     * <nl>
     * Asynchronous version.
     */
    public final of4gwt.misc.Future<java.lang.String> loginAsync(java.lang.String username, java.lang.String password, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.String> callback) {
        return loginAsync(username, password, callback, getDefaultAsyncOptions_objectfabric(), getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Creates a session
     * <nl>
     * Asynchronous version, with options for the callback.
     */
    public final of4gwt.misc.Future<java.lang.String> loginAsync(java.lang.String username, java.lang.String password, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.String> callback, of4gwt.AsyncOptions asyncOptions) {
        return loginAsync(username, password, callback, asyncOptions, getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Creates a session
     * <nl>
     * Asynchronous version, with options for the callback, and specifies the Executor or TaskScheduler that will run the method. For replicated objects,
     * the method runs by default on the site the object has been created. @see Site.getMethodExecutor() to specify an execution site.
     */
    public final of4gwt.misc.Future<java.lang.String> loginAsync(java.lang.String username, java.lang.String password, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.String> callback, of4gwt.AsyncOptions asyncOptions, of4gwt.misc.Executor executor) {
        if (executor == of4gwt.misc.TransparentExecutor.getInstance()) {
            java.lang.String result_ = null;
            java.lang.Exception exception_ = null;

            try {
                result_ = loginImplementation(username, password);
            } catch (java.lang.Exception e_) {
                exception_ = e_;
            }

            return getCompletedFuture_objectfabric(result_, exception_, callback, asyncOptions);
        } else {
            of4gwt.ShiroObjectModel.Method3.Version version_ = (of4gwt.ShiroObjectModel.Method3.Version) createVersion_objectfabric(of4gwt.ShiroObjectModel.Method3.INSTANCE);

            if (username != null) {
                version_._username = username;
                version_.setBit(of4gwt.ShiroObjectModel.Method3.USERNAME_INDEX);
            }

            if (password != null) {
                version_._password = password;
                version_.setBit(of4gwt.ShiroObjectModel.Method3.PASSWORD_INDEX);
            }

            of4gwt.TObject.UserTObject.LocalMethodCall call_ = new of4gwt.TObject.UserTObject.LocalMethodCall(this, of4gwt.ShiroObjectModel.Method3.INSTANCE, version_, METHOD_0, callback, asyncOptions);
            executor.execute(call_);
            return call_;
        }
    }

    /**
     * Override to implement the method.
     */
    protected java.lang.String loginImplementation(java.lang.String username, java.lang.String password) {
        throw new RuntimeException(of4gwt.Strings.MISSING_METHOD_CALL_IMPLEMENTATION);
    }

    /**
     * Override to implement the method asynchronously.
     */
    protected void loginImplementationAsync(java.lang.String username, java.lang.String password, of4gwt.MethodCall call) {
        try {
            call.set(loginImplementation(username, password));
        } catch (java.lang.Exception e_) {
            call.setException(e_);
        }
    }

    /**
     * Binds to existing session
     * <nl>
     * Asynchronous version.
     */
    public final of4gwt.misc.Future<java.lang.Void> bindAsync(java.lang.String session, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback) {
        return bindAsync(session, callback, getDefaultAsyncOptions_objectfabric(), getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Binds to existing session
     * <nl>
     * Asynchronous version, with options for the callback.
     */
    public final of4gwt.misc.Future<java.lang.Void> bindAsync(java.lang.String session, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback, of4gwt.AsyncOptions asyncOptions) {
        return bindAsync(session, callback, asyncOptions, getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Binds to existing session
     * <nl>
     * Asynchronous version, with options for the callback, and specifies the Executor or TaskScheduler that will run the method. For replicated objects,
     * the method runs by default on the site the object has been created. @see Site.getMethodExecutor() to specify an execution site.
     */
    public final of4gwt.misc.Future<java.lang.Void> bindAsync(java.lang.String session, com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback, of4gwt.AsyncOptions asyncOptions, of4gwt.misc.Executor executor) {
        if (executor == of4gwt.misc.TransparentExecutor.getInstance()) {
            java.lang.Void result_ = null;
            java.lang.Exception exception_ = null;

            try {
                bindImplementation(session);
            } catch (java.lang.Exception e_) {
                exception_ = e_;
            }

            return getCompletedFuture_objectfabric(result_, exception_, callback, asyncOptions);
        } else {
            of4gwt.ShiroObjectModel.Method4.Version version_ = (of4gwt.ShiroObjectModel.Method4.Version) createVersion_objectfabric(of4gwt.ShiroObjectModel.Method4.INSTANCE);

            if (session != null) {
                version_._session = session;
                version_.setBit(of4gwt.ShiroObjectModel.Method4.SESSION_INDEX);
            }

            of4gwt.TObject.UserTObject.LocalMethodCall call_ = new of4gwt.TObject.UserTObject.LocalMethodCall(this, of4gwt.ShiroObjectModel.Method4.INSTANCE, version_, METHOD_1, callback, asyncOptions);
            executor.execute(call_);
            return call_;
        }
    }

    /**
     * Override to implement the method.
     */
    protected void bindImplementation(java.lang.String session) {
        throw new RuntimeException(of4gwt.Strings.MISSING_METHOD_CALL_IMPLEMENTATION);
    }

    /**
     * Override to implement the method asynchronously.
     */
    protected void bindImplementationAsync(java.lang.String session, of4gwt.MethodCall call) {
        try {
            bindImplementation(session);
            call.set(null);
        } catch (java.lang.Exception e_) {
            call.setException(e_);
        }
    }

    /**
     * Deletes current session
     * <nl>
     * Asynchronous version.
     */
    public final of4gwt.misc.Future<java.lang.Void> logoutAsync(com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback) {
        return logoutAsync(callback, getDefaultAsyncOptions_objectfabric(), getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Deletes current session
     * <nl>
     * Asynchronous version, with options for the callback.
     */
    public final of4gwt.misc.Future<java.lang.Void> logoutAsync(com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback, of4gwt.AsyncOptions asyncOptions) {
        return logoutAsync(callback, asyncOptions, getDefaultMethodExecutor_objectfabric());
    }

    /**
     * Deletes current session
     * <nl>
     * Asynchronous version, with options for the callback, and specifies the Executor or TaskScheduler that will run the method. For replicated objects,
     * the method runs by default on the site the object has been created. @see Site.getMethodExecutor() to specify an execution site.
     */
    public final of4gwt.misc.Future<java.lang.Void> logoutAsync(com.google.gwt.user.client.rpc.AsyncCallback<java.lang.Void> callback, of4gwt.AsyncOptions asyncOptions, of4gwt.misc.Executor executor) {
        if (executor == of4gwt.misc.TransparentExecutor.getInstance()) {
            java.lang.Void result_ = null;
            java.lang.Exception exception_ = null;

            try {
                logoutImplementation();
            } catch (java.lang.Exception e_) {
                exception_ = e_;
            }

            return getCompletedFuture_objectfabric(result_, exception_, callback, asyncOptions);
        } else {
            of4gwt.ShiroObjectModel.Method5.Version version_ = (of4gwt.ShiroObjectModel.Method5.Version) createVersion_objectfabric(of4gwt.ShiroObjectModel.Method5.INSTANCE);

            of4gwt.TObject.UserTObject.LocalMethodCall call_ = new of4gwt.TObject.UserTObject.LocalMethodCall(this, of4gwt.ShiroObjectModel.Method5.INSTANCE, version_, METHOD_2, callback, asyncOptions);
            executor.execute(call_);
            return call_;
        }
    }

    /**
     * Override to implement the method.
     */
    protected void logoutImplementation() {
        throw new RuntimeException(of4gwt.Strings.MISSING_METHOD_CALL_IMPLEMENTATION);
    }

    /**
     * Override to implement the method asynchronously.
     */
    protected void logoutImplementationAsync(of4gwt.MethodCall call) {
        try {
            logoutImplementation();
            call.set(null);
        } catch (java.lang.Exception e_) {
            call.setException(e_);
        }
    }

    @SuppressWarnings({ "static-access", "cast" })
    @Override
    protected void invoke_objectfabric(of4gwt.MethodCall call) {
        switch (getMethodCallIndex_objectfabric(call)) {
            case METHOD_0: {
                of4gwt.ShiroObjectModel.Method3.Version version_ = (of4gwt.ShiroObjectModel.Method3.Version) getMethodVersion_objectfabric(call);
                java.lang.String username = version_ != null ? (java.lang.String) version_._username : null;
                java.lang.String password = version_ != null ? (java.lang.String) version_._password : null;

                try {
                    loginImplementationAsync(username, password, call);
                } catch (java.lang.Exception e_) {
                    call.setException(e_);
                }

                break;
            }
            case METHOD_1: {
                of4gwt.ShiroObjectModel.Method4.Version version_ = (of4gwt.ShiroObjectModel.Method4.Version) getMethodVersion_objectfabric(call);
                java.lang.String session = version_ != null ? (java.lang.String) version_._session : null;

                try {
                    bindImplementationAsync(session, call);
                } catch (java.lang.Exception e_) {
                    call.setException(e_);
                }

                break;
            }
            case METHOD_2: {
                try {
                    logoutImplementationAsync(call);
                } catch (java.lang.Exception e_) {
                    call.setException(e_);
                }

                break;
            }
            default: {
                super.invoke_objectfabric(call);
                break;
            }
        }
    }

    @SuppressWarnings({ "static-access", "cast" })
    @Override
    protected void setResult_objectfabric(of4gwt.TObject.Version version, int index, java.lang.Object result) {
        switch (index) {
            case METHOD_0: {
                ((of4gwt.ShiroObjectModel.Method3.Version) version)._return_objectfabric = (java.lang.String) result;
                ((of4gwt.ShiroObjectModel.Method3.Version) version).setBit(of4gwt.ShiroObjectModel.Method3.RETURN_OBJECTFABRIC_INDEX);
                break;
            }
            case METHOD_1: {
                break;
            }
            case METHOD_2: {
                break;
            }
            default: {
                super.setResult_objectfabric(version, index, result);
                break;
            }
        }
    }

    @SuppressWarnings("static-access")
    @Override
    protected void setError_objectfabric(of4gwt.TObject.Version version, int index, java.lang.String error) {
        switch (index) {
            case METHOD_0: {
                ((of4gwt.ShiroObjectModel.Method3.Version) version)._error_objectfabric = error;
                ((of4gwt.ShiroObjectModel.Method3.Version) version).setBit(of4gwt.ShiroObjectModel.Method3.ERROR_OBJECTFABRIC_INDEX);
                break;
            }
            case METHOD_1: {
                ((of4gwt.ShiroObjectModel.Method4.Version) version)._error_objectfabric = error;
                ((of4gwt.ShiroObjectModel.Method4.Version) version).setBit(of4gwt.ShiroObjectModel.Method4.ERROR_OBJECTFABRIC_INDEX);
                break;
            }
            case METHOD_2: {
                ((of4gwt.ShiroObjectModel.Method5.Version) version)._error_objectfabric = error;
                ((of4gwt.ShiroObjectModel.Method5.Version) version).setBit(of4gwt.ShiroObjectModel.Method5.ERROR_OBJECTFABRIC_INDEX);
                break;
            }
            default: {
                super.setError_objectfabric(version, index, error);
                break;
            }
        }
    }

    @SuppressWarnings("static-access")
    @Override
    protected void getResultOrError_objectfabric(of4gwt.MethodCall call) {
        switch (getMethodCallIndex_objectfabric(call)) {
            case METHOD_0: {
                of4gwt.ShiroObjectModel.Method3.Version version = (of4gwt.ShiroObjectModel.Method3.Version) getMethodVersion_objectfabric(call);

                if (version == null || version._error_objectfabric == null)
                    setDirect(call, version != null ? version._return_objectfabric : null);
                else
                    setExceptionDirect(call, new of4gwt.misc.ReplicatedException(version._error_objectfabric));

                break;
            }
            case METHOD_1: {
                of4gwt.ShiroObjectModel.Method4.Version version = (of4gwt.ShiroObjectModel.Method4.Version) getMethodVersion_objectfabric(call);

                if (version == null || version._error_objectfabric == null)
                    setDirect(call, null);
                else
                    setExceptionDirect(call, new of4gwt.misc.ReplicatedException(version._error_objectfabric));

                break;
            }
            case METHOD_2: {
                of4gwt.ShiroObjectModel.Method5.Version version = (of4gwt.ShiroObjectModel.Method5.Version) getMethodVersion_objectfabric(call);

                if (version == null || version._error_objectfabric == null)
                    setDirect(call, null);
                else
                    setExceptionDirect(call, new of4gwt.misc.ReplicatedException(version._error_objectfabric));

                break;
            }
            default: {
                super.getResultOrError_objectfabric(call);
                break;
            }
        }
    }

    protected static class Version extends of4gwt.TGeneratedFields32.Version {

        public of4gwt.TObject _userManager;

        private static final int _readOnlys;

        static {
            int readOnlys = 0;
            readOnlys = setBit(readOnlys, USER_MANAGER_INDEX);
            _readOnlys = readOnlys;
        }

        public Version(of4gwt.TGeneratedFields32.Version shared, int length) {
            super(shared, length);
        }

        @Override
        public java.lang.Object getAsObject(int index) {
            switch (index) {
                case USER_MANAGER_INDEX:
                    return getUserTObject_objectfabric(_userManager);
                default:
                    return super.getAsObject(index);
            }
        }

        @Override
        public void setAsObject(int index, java.lang.Object value) {
            switch (index) {
                case USER_MANAGER_INDEX:
                    _userManager = (of4gwt.UsernamePasswordUserManager) value;
                    break;
                default:
                    super.setAsObject(index, value);
                    break;
            }
        }

        @Override
        public of4gwt.TObject.Version merge(of4gwt.TObject.Version target, of4gwt.TObject.Version next, int flags) {
            UsernamePasswordSession.Version source = (UsernamePasswordSession.Version) next;
            UsernamePasswordSession.Version merged = (UsernamePasswordSession.Version) super.merge(target, next, flags);

            if (source.hasBits()) {
                if (source.getBit(USER_MANAGER_INDEX))
                    merged._userManager = mergeTObject(merged._userManager, source._userManager);
            }

            return merged;
        }

        @Override
        public int getReadOnlys() {
            return _readOnlys;
        }

        @Override
        public void writeWrite(of4gwt.Writer writer, int index) {
            if (writer.interrupted())
                writer.resume();

            switch (index) {
                case USER_MANAGER_INDEX: {
                    writer.writeTObject(_userManager);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
                default: {
                    super.writeWrite(writer, index);

                    if (writer.interrupted()) {
                        writer.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public void readWrite(of4gwt.Reader reader, int index) {
            if (reader.interrupted())
                reader.resume();

            switch (index) {
                case USER_MANAGER_INDEX: {
                    UsernamePasswordSession.Version shared = (UsernamePasswordSession.Version) getUnion();
                    shared._userManager = getSharedVersion_objectfabric(reader.readTObject());

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }

                    shared.setBit(USER_MANAGER_INDEX);
                    unsetBit(USER_MANAGER_INDEX);
                    break;
                }
                default: {
                    super.readWrite(reader, index);

                    if (reader.interrupted()) {
                        reader.interrupt(null);
                        return;
                    }
                    break;
                }
            }
        }

        @Override
        public of4gwt.TObject.Version createVersion() {
            return new UsernamePasswordSession.Version(this, FIELD_COUNT);
        }

        @Override
        public int getClassId() {
            return of4gwt.ShiroObjectModel.OF4GWT_USERNAMEPASSWORDSESSION_CLASS_ID;
        }

        @SuppressWarnings("static-access")
        @Override
        public of4gwt.ObjectModel getObjectModel() {
            return of4gwt.ShiroObjectModel.getInstance();
        }
    }
}
